spring:
  config:
    import: "application-private.yml"
  main:
    allow-circular-references: false
    #allow-bean-definition-overriding: false

  application:
    name: image
  # mysql 연동을 위해 기초 metadata 입력
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 스프링부트 2.1 이후부턴 MODE = MYSQL 작성 필수 -> 이건 H2내장 데이터베이스 쓸 경우를 의미
    url: jdbc:mysql://picto-db-2.cj8eomgw4s4w.ap-northeast-2.rds.amazonaws.com:3306/photo_schema
    username: admin
    password: rlatmdals456!

  sql:
    init:
      mode: always

  security:
    enabled: false
  #    user:
  #      name: user
  #      password: 1234

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
      # 테이블 이름을 명시한데로 대소문자 구분해서 표현하기
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #defer-datasource-initialization: true
    show-sql: true

    #    properties:
    #      hibernate:
    #        format_sql: true
    #        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    open-in-view: false

#
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      force-response: true

  port: 8084

session:
  scheduler:
    enabled: true
    base-url: http://52.79.109.62:8085
